import { mutation } from "./_generated/server";

export const seedAll = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if already seeded
    const existing = await ctx.db.query("keyResults").first();
    if (existing) return "Already seeded";

    // Seed Lists
    const lists = [
      { category: "owners", values: ["MEC", "HWS", "Head of Nutrition", "Sales Lead", "FOH Manager", "Coworking Lead", "Finance", "Marketing", "Community Lead", "F&B Manager", "Product", "GM", "HR", "Lab Lead", "Fitness Lead", "Retail Lead", "WellnessLab Lead", "Recovery Lead"] },
      { category: "frequencies", values: ["Weekly", "Monthly", "Quarterly"] },
      { category: "directions", values: ["Increase", "Decrease", "Milestone"] },
      { category: "statuses", values: ["No data", "Achieved", "On track", "Watch", "Off track"] },
      { category: "departments", values: ["Community", "F&B", "Finance", "Fitness", "Lab", "Marketing", "Member Experience", "Member Experience & Wellness", "Member Success", "Nutrition", "Nutrition + F&B", "Operations", "People & Culture", "Product", "Product & Coaching", "Retail", "Sales", "Sales + MEC", "Tech & CX", "Wellness Science", "WellnessLab"] },
    ];
    for (const list of lists) {
      await ctx.db.insert("lists", list);
    }

    // Seed Objectives
    const objectives = [
      { objectiveId: "O1", name: "Change the lives of 1,000 people by end of 2027" },
      { objectiveId: "O2", name: "Grow Omni membership while increasing long-term commitment" },
      { objectiveId: "O3", name: "Be the best in the world - best facility, best service, most advanced wellness offering" },
      { objectiveId: "O4", name: "Build an incredible community & environment for members and staff" },
      { objectiveId: "O5", name: "Grow the Omni cafe and wellness food ecosystem" },
      { objectiveId: "O6", name: "Make the Omni brand synonymous with being world's most advanced wellness club" },
      { objectiveId: "O7", name: "Improve operational efficiency and profitability" },
      { objectiveId: "O8", name: "Build a high-performing Omni team and culture" },
      { objectiveId: "O9", name: "Build a world-class Omni member experience" },
      { objectiveId: "O10", name: "Increase average revenue per member in relation to monthly WMAM" },
      { objectiveId: "O11", name: "Increase Head of Nutrition activity" },
    ];
    for (const obj of objectives) {
      await ctx.db.insert("objectives", obj);
    }

    // Seed Key Results
    const keyResults = [
      { krId: "KR-001", krType: "Aspirational", objectiveId: "O1", objective: "Change the lives of 1,000 people by end of 2027", department: "GM / FOH / MEC / Marketing", keyResult: "Have 1,000 people go through our PWP journey", dataSource: "GymMaster / MEC system", baseline: "200", target: "1000", actualCurrent: "260", progressPercent: 0.075, status: "Off track", owner: "GM / FOH / MEC", reportingTo: "Connor", reviewFrequency: "Weekly", how: "1. Have 25% of our marketing focus on personalized wellness services\n2. MEC activity\n3. Front desk tour conversion\n4. Weekly new-member coffee\n5. Incentive for completion\n6. Incomplete-onboarding queue reviewed every Monday\n7. Referral benefits", notes: "Currently around 200 completed", section: "main" },
      { krId: "KR-002", krType: "Committed", objectiveId: "O1", objective: "Change the lives of 1,000 people by end of 2027", department: "GM / FOH / Marketing / WellnessLab", keyResult: "Increase clinic sales by 10% per quarter", dataSource: "Finance report", baseline: "175000000", target: "192500000", actualCurrent: "182000000", progressPercent: 0.4, status: "Watch", owner: "GM / FOH / MEC", reportingTo: "Connor", reviewFrequency: "Weekly", how: "1. Bundle blood panel + IV + 3D scan\n2. Internal referrals from trainers/FOH\n3. MEC activity\n4. Two workshops a month with CTA\n5. Launch mini PWP with 4 week members", notes: "Currently around 175m a month in revenue", section: "main" },
      { krId: "KR-003", krType: "Committed", objectiveId: "O1", objective: "Change the lives of 1,000 people by end of 2027", department: "HWS", keyResult: "Increase follow-up consultations with HWS by 25% per quarter", dataSource: "GymMaster", baseline: "2", target: "25% above baseline", actualCurrent: "4", progressPercent: 4, status: "Achieved", owner: "HWS / HCs", reportingTo: "Henry", reviewFrequency: "Monthly", how: "1. Sell 12-week follow-up package\n2. Pre-book next consult before member leaves\n3. Automated 2-week follow-up reminder\n4. Progress review template", notes: "Track as follow-up consults / total initial consults", section: "main" },
      { krId: "KR-004", krType: "Committed", objectiveId: "O1", objective: "Change the lives of 1,000 people by end of 2027", department: "HON", keyResult: "Increase nutritionist bookings +25% per quarter", dataSource: "GymMaster", baseline: "", target: "25% above baseline", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Head of Nutrition", reportingTo: "Connor", reviewFrequency: "Monthly", how: "1. One workshop with CTA per month\n2. Marketing focus on wellness services\n3. Launch mini PWP\n4. Increase marketing by 10%", notes: "Head of Nutrition suggests 5-10 initial consults/month", section: "main" },
      { krId: "KR-005", krType: "Committed", objectiveId: "O1", objective: "Change the lives of 1,000 people by end of 2027", department: "Member Experience Concierge (MEC)", keyResult: "Increase % of 4 week+ members using at least one personalized wellness service by 10% per quarter", dataSource: "GymMaster", baseline: "", target: "10% above baseline", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Member Experience Concierge (MEC)", reportingTo: "Connor", reviewFrequency: "Monthly", how: "1. Marketing focus on personalized wellness\n2. MEC activity (deals/upgrade nudges, welcome flow)\n3. Front desk tour conversion\n4. Weekly new-member coffee\n5. Incentive for completion\n6. Incomplete queue reviewed by HCs\n7. Two wellness workshops a month", section: "main" },
      { krId: "KR-006", krType: "Committed", objectiveId: "O1", objective: "Change the lives of 1,000 people by end of 2027", department: "Marketing", keyResult: "Create great marketing content/campaigns around the clinic - inc 4 documented member transformations per quarter", dataSource: "Marketing + wellness team", baseline: "", target: "20", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Marketing", reportingTo: "Henry", reviewFrequency: "Monthly", how: "1. Full marketing strategy and content plan for clinic\n2. Transformation tracker\n3. Baseline-action-result template\n4. Monthly review of candidates\n5. Consent workflow\n6. Prioritize stories with objective metrics", section: "main" },
      { krId: "KR-007", krType: "Committed", objectiveId: "O1", objective: "Change the lives of 1,000 people by end of 2027", department: "Events & Marketing", keyResult: "Sell at least 60 retreat spots per year", dataSource: "Xendit sales from Adit", baseline: "", target: "60 sales/year (4-6 retreats x 10-15 people)", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Events", reportingTo: "Henry", reviewFrequency: "Weekly", how: "1. Create great retreat itinerary\n2. Create great website\n3. Create great ads\n4. A/B test ads\n5. Detailed planning + amazing execution", section: "main" },
      { krId: "KR-008", krType: "Aspirational", objectiveId: "O2", objective: "Grow Omni membership while increasing long-term commitment", department: "FOH / MEC / marketing", keyResult: "Reach 1,500 WMAM in 2026", dataSource: "GymMaster", baseline: "1100", target: "1500", actualCurrent: "1300", progressPercent: 0.5, status: "Watch", owner: "GM / FOH / MEC", reportingTo: "Connor", reviewFrequency: "Weekly", how: "1. MEC activity (We miss you)\n2. Referral program\n3. Increase marketing activity by 10% per quarter\n4. Increase tour conversion by 10%\n5. Increase partnerships by 10%", section: "main" },
      { krId: "KR-009", krType: "Committed", objectiveId: "O2", objective: "Grow Omni membership while increasing long-term commitment", department: "FOH", keyResult: "Increase 'revenue per tour' (RPT) by 10% by end of Q3 2026", dataSource: "From FOH", baseline: "", target: "25% above baseline", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "GM / FOH", reportingTo: "Henry", reviewFrequency: "Weekly", how: "1. Ensure script is good\n2. Create 1-pager summary\n3. Check tour quality\n4. Personalize tour by goal\n5. Close with consult/booking\n6. Immediate WA follow-up\n7. Use testimonials\n8. Daily lost-tour review", section: "main" },
      { krId: "KR-010", krType: "Aspirational", objectiveId: "O2", objective: "Grow Omni membership while increasing long-term commitment", department: "FOH / MEC", keyResult: "Increase long-term memberships from 36.81% to 50% of membership base in 2026", dataSource: "GymMaster", baseline: "0.3681", target: "0.5", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "GM / FOH / MEC", reportingTo: "Connor", reviewFrequency: "Monthly", how: "1. All-In elevation scripts for tours\n2. Increase marketing for All-in\n3. MEC activity\n4. Create comparison materials", section: "main" },
      { krId: "KR-011", krType: "Committed", objectiveId: "O2", objective: "Grow Omni membership while increasing long-term commitment", department: "FOH / MEC / Co-working / Marketing", keyResult: "Increase co-working membership to 150 WMAM in 2026", dataSource: "GymMaster", baseline: "80", target: "150", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Coworking Lead / MEC", reportingTo: "Connor", reviewFrequency: "Monthly", how: "1. Dual membership discount\n2. Marketing for co-working\n3. Referral program\n4. Free coworking weeks for yearly members\n5. Nomad community events\n6. Partnerships with villas/hotels\n7. Train + work bundles", section: "main" },
      { krId: "KR-012", krType: "Committed", objectiveId: "O2", objective: "Grow Omni membership while increasing long-term commitment", department: "Finance", keyResult: "Increase average revenue per member by 10% per quarter", dataSource: "Finance report", baseline: "", target: "Set by finance", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "GM / Cafe Manager / Marketing", reportingTo: "Connor", reviewFrequency: "Monthly", how: "1. Achieve OKR 04\n2. Increase F&B\n3. Marketing of services\n4. Staff upsell training\n5. Add bundles\n6. Merch sales\n7. PT conversion", section: "main" },
      { krId: "KR-013", krType: "Committed", objectiveId: "O2", objective: "Grow Omni membership while increasing long-term commitment", department: "FOH / marketing", keyResult: "Increase referral-based memberships by 10% per month", dataSource: "From FOH", baseline: "", target: "10% above baseline", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "GM / FOH", reportingTo: "Connor", reviewFrequency: "Monthly", how: "1. Referral program\n2. Guest pass tracking\n3. Referral code/source capture\n4. Monthly leaderboard for staff", section: "main" },
      { krId: "KR-014", krType: "Committed", objectiveId: "O2", objective: "Grow Omni membership while increasing long-term commitment", department: "FOH", keyResult: "10% increase in 12-week+ Core and All-in sales by end of Q3 2026", dataSource: "GymMaster", baseline: "", target: "10% above baseline", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "GM / FOH", reportingTo: "Henry", reviewFrequency: "Monthly", how: "1. FOH leads with longer-term value\n2. Floor staff nudge members nearing expiry\n3. Targeted win-back to All-In\n4. MEC activity\n5. Create 1-pager summary\n6. Check tour quality", section: "main" },
      { krId: "KR-015", krType: "Committed", objectiveId: "O3", objective: "Be the best in the world - best facility, best service, most advanced wellness offering", department: "FOH / marketing / Martin / F&B", keyResult: "Achieve Google Review score of 4.8 by end of Q3 2026", dataSource: "From FOH", baseline: "4.7", target: "4.8", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "GM / FOH", reportingTo: "Henry", reviewFrequency: "Monthly", how: "1. Automated review ask after high-satisfaction\n2. Automated review ask on story posts\n3. Review QR at front desk\n4. Recovery plan for unhappy members\n5. Reply to all reviews\n6. FOH & F&B staff ask for reviews", section: "main" },
      { krId: "KR-016", krType: "Committed", objectiveId: "O3", objective: "Be the best in the world - best facility, best service, most advanced wellness offering", department: "Marketing / GM / F&B", keyResult: "250+ 5 star reviews on GoJek & Grab", dataSource: "Marketing manager", baseline: "", target: "250", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Marketing", reportingTo: "Henry", reviewFrequency: "Monthly", how: "1. Review request inserts in delivery bag\n2. Follow-up message or sticker QR\n3. Rapid response to issues\n4. Staff accuracy checks", section: "main" },
      { krId: "KR-017", krType: "Committed", objectiveId: "O3", objective: "Be the best in the world - best facility, best service, most advanced wellness offering", department: "Marketing / GM / F&B", keyResult: "400+ 5star reviews on Omni Kitchen", dataSource: "Marketing manager", baseline: "", target: "400", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Marketing", reportingTo: "Henry", reviewFrequency: "Monthly", how: "1. In-store QR review ask\n2. Ask after positive meal-plan feedback\n3. Highlight review goal to staff\n4. Weekly reply to reviews", section: "main" },
      { krId: "KR-018", krType: "Committed", objectiveId: "O3", objective: "Be the best in the world - best facility, best service, most advanced wellness offering", department: "Marketing", keyResult: "Feature 'Meet Your Wellness expert' Series 1-2 per month", dataSource: "Marketing dept", baseline: "0", target: "1-2 / month", actualCurrent: "0.395", progressPercent: 0.395, status: "Achieved", owner: "Marketing", reportingTo: "Henry", reviewFrequency: "Monthly", how: "1. Short-form video templates\n2. Schedule monthly filming day\n3. Topics from FAQs/myths/biomarkers\n4. Add CTA to book consult", section: "main" },
      { krId: "KR-019", krType: "Committed", objectiveId: "O3", objective: "Be the best in the world - best facility, best service, most advanced wellness offering", department: "AI", keyResult: "Launch digital PWP by end of Q3 2026", dataSource: "Digital onboarding completion", baseline: "0", target: "1", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "AI", reportingTo: "Henry", reviewFrequency: "Weekly", how: "1. Scope MVP\n2. Define template library\n3. Assign content owners\n4. Test with pilot users\n5. Train staff\n6. Launch with feedback loop", notes: "Milestone KPI: 0 not launched, 1 launched", section: "main" },
      { krId: "KR-020", krType: "Aspirational", objectiveId: "O3", objective: "Be the best in the world - best facility, best service, most advanced wellness offering", department: "AI", keyResult: "Leverage AI throughout the business", dataSource: "", baseline: "", target: "Set target days", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "AI", reportingTo: "Connor", reviewFrequency: "Monthly", how: "1. Template bank\n2. AI-assisted draft with manual review\n3. SLA by role\n4. Dashboard of overdue PWPs\n5. Daily owner assignment", section: "main" },
      { krId: "KR-021", krType: "Committed", objectiveId: "O3", objective: "Be the best in the world - best facility, best service, most advanced wellness offering", department: "Nutrition + F&B", keyResult: "Increase nutrition app adoption", dataSource: "App MAU", baseline: "", target: "Set by Product", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Nutrition + F&B", reportingTo: "Henry", reviewFrequency: "Monthly", how: "1. QR activation at join\n2. App-first booking benefits\n3. MEC prompts\n4. Simplify sign-up\n5. Track drop-off by step", section: "main" },
      { krId: "KR-022", krType: "Committed", objectiveId: "O3", objective: "Be the best in the world - best facility, best service, most advanced wellness offering", department: "AI", keyResult: "Integrate wearables tracking", dataSource: "Wearable-linked members", baseline: "", target: "Set by Product", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "AI", reportingTo: "Connor", reviewFrequency: "Monthly", how: "1. Start with 1-2 integrations\n2. Clear use cases\n3. Onboarding tutorial\n4. HWS uses data in consults", section: "main" },
      { krId: "KR-023", krType: "Committed", objectiveId: "O4", objective: "Build an incredible community & environment", department: "GM / FOH / MEC / Trainers", keyResult: "Increase average visits per member per week to 5+", dataSource: "GymMaster", baseline: ">3.0", target: ">3.0", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Member Experience Concierge (MEC)", reportingTo: "Connor", reviewFrequency: "Weekly", how: "1. Inactivity nudges at 5+ days\n2. 'What should we book you into?' messages\n3. Class reminders\n4. Attendance streak recognition\n5. Personalized activity recommendations", notes: "Currently 3.65/week", section: "main" },
      { krId: "KR-024", krType: "Committed", objectiveId: "O4", objective: "Build an incredible community & environment", department: "Member Experience Concierge (MEC)", keyResult: "Increase renewal conversion rate by 10% per month", dataSource: "MEC system", baseline: "", target: "10% above baseline", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Member Experience Concierge (MEC)", reportingTo: "Connor", reviewFrequency: "Weekly", how: "1. Day -5/-1 renewal messages\n2. Auto-renew bonus days\n3. Roll short passes into longer terms\n4. All-In upgrade offers\n5. Follow-up 48h later", section: "main" },
      { krId: "KR-025", krType: "Aspirational", objectiveId: "O4", objective: "Build an incredible community & environment", department: "Member Experience Concierge (MEC)", keyResult: "Increase long-term memberships from 36.81% to 50%", dataSource: "MEC system", baseline: "0.3681", target: "0.5", actualCurrent: "0.2", progressPercent: -1.274, status: "Off track", owner: "Member Experience Concierge (MEC)", reportingTo: "Connor", reviewFrequency: "Monthly", how: "1. MEC renewal flow to longer terms\n2. Track mini PWP conversions\n3. All-In benefits framing\n4. Loyalty perks\n5. Rollover unused days\n6. Comparison of effective monthly value", section: "main" },
      { krId: "KR-026", krType: "Committed", objectiveId: "O4", objective: "Build an incredible community & environment", department: "Member Experience Concierge (MEC)", keyResult: "Increase % of members with 20+ check-ins/month", dataSource: "GymMaster", baseline: "0.1", target: "0.25", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Member Experience Concierge (MEC)", reportingTo: "Connor", reviewFrequency: "Monthly", how: "1. Streak rewards\n2. Top-attendee recognition\n3. Class reminders\n4. Custom plans for low-frequency members\n5. Follow-up 48h later", section: "main" },
      { krId: "KR-027", krType: "Committed", objectiveId: "O4", objective: "Build an incredible community & environment", department: "Member Experience Concierge (MEC)", keyResult: "Increase expired member win-back rate by 10% per month", dataSource: "MEC system", baseline: "", target: "10% above baseline", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Member Experience Concierge (MEC)", reportingTo: "Connor", reviewFrequency: "Monthly", how: "1. 4-weeks-post-expiry 'we miss you' flow\n2. Perk-based reactivation offers\n3. 2 follow-ups 48h apart\n4. Segment offers by prior membership length", section: "main" },
      { krId: "KR-028", krType: "Committed", objectiveId: "O4", objective: "Build an incredible community & environment", department: "Events / marketing / MEC", keyResult: "Increase event/community attendance by X% by end of Q2 2026", dataSource: "GymMaster", baseline: "", target: "Set by events team", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Community Lead", reportingTo: "Connor", reviewFrequency: "Monthly", how: "1. Monthly event calendar\n2. Holiday-led activations\n3. Guest-pass events\n4. Event invites in MEC flow\n5. Event-to-membership CTA\n6. Post-event follow-up", section: "main" },
      { krId: "KR-029", krType: "Committed", objectiveId: "O4", objective: "Build an incredible community & environment", department: "Member Experience Concierge (MEC)", keyResult: "Increase conversion rate of MEC system to 10%", dataSource: "MEC system", baseline: "", target: "0.1", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Member Experience Concierge (MEC)", reportingTo: "Connor", reviewFrequency: "Weekly", how: "1. Track every message sequence\n2. A/B test copy/perks/timing\n3. One clear CTA per message\n4. Cap discount frequency\n5. Review conversion weekly", section: "main" },
      { krId: "KR-030", krType: "Committed", objectiveId: "O5", objective: "Grow the Omni cafe and wellness food ecosystem", department: "F&B", keyResult: "Increase daily F&B sales to 110m IDR by end of Q2 2026", dataSource: "Finance report", baseline: "", target: "110000000", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "F&B Manager / GM", reportingTo: "C&H", reviewFrequency: "Weekly", how: "1. Increase marketing\n2. Improve operational structure\n3. Add call buttons/table ordering\n4. Improve menu engineering\n5. Sell recovery/protein hero products", section: "main" },
      { krId: "KR-031", krType: "Committed", objectiveId: "O5", objective: "Grow the Omni cafe and wellness food ecosystem", department: "F&B", keyResult: "Achieve GoJek/Grab daily sales of 25m IDR by end of Q2 2026", dataSource: "Finance report", baseline: "", target: "25000000", actualCurrent: "23000", progressPercent: undefined, status: "Achieved", owner: "F&B Manager / GM", reportingTo: "C&H", reviewFrequency: "Weekly", how: "1. Optimize delivery menu\n2. Improve photos\n3. Incentivize reviews\n4. Run platform promos\n5. Prep operational flow\n6. Test hero bundles", section: "main" },
      { krId: "KR-032", krType: "Aspirational", objectiveId: "O5", objective: "Grow the Omni cafe and wellness food ecosystem", department: "Nutrition + F&B", keyResult: "Increase meal plan orders to 10 a month by end of Q2 2026", dataSource: "Finance report", baseline: "", target: "10", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Head of Nutrition", reportingTo: "C&H", reviewFrequency: "Monthly", how: "1. Offer pre-made goal-based meals\n2. First-week discounted trial\n3. Consult upsell scripts\n4. WA follow-up after consult\n5. Collect blockers", section: "main" },
      { krId: "KR-033", krType: "Committed", objectiveId: "O5", objective: "Grow the Omni cafe and wellness food ecosystem", department: "F&B", keyResult: "Improve F&B COGS to 30% by end of Q3 2026", dataSource: "Finance report", baseline: "", target: "0.3", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "F&B Manager / F&B Purchasing / GM", reportingTo: "C&H", reviewFrequency: "Monthly", how: "1. Menu margin review\n2. Supplier renegotiation\n3. Portion control\n4. Waste tracking\n5. Remove low-margin slow movers\n6. Standard recipe cards\n7. Daily discounts for expiring ingredients", section: "main" },
      { krId: "KR-034", krType: "Committed", objectiveId: "O5", objective: "Grow the Omni cafe and wellness food ecosystem", department: "F&B", keyResult: "Increase average order value by 10% by end of Q2 2026", dataSource: "Finance report", baseline: "", target: "10% above baseline", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "F&B Manager", reportingTo: "C&H", reviewFrequency: "Weekly", how: "1. Combo offers\n2. Add-on prompts at POS\n3. Hero-product placement\n4. Upsell scripts\n5. Meal + drink bundles\n6. Merch/grab-and-go pairing\n7. Better menu design", section: "main" },
      { krId: "KR-035", krType: "Committed", objectiveId: "O6", objective: "Make the Omni brand synonymous with being world's most advanced wellness club", department: "Marketing", keyResult: "Increase adverts on IG by 10% / Improve Google SEO by end of Q3 2026", dataSource: "Marketing dept", baseline: "", target: "10% above baseline", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Marketing", reportingTo: "Henry", reviewFrequency: "Monthly", how: "1. Paid IG creative testing\n2. Local SEO pages\n3. Google Business optimization\n4. Increase content velocity\n5. Geo-targeted campaigns\n6. Map pack optimization", section: "main" },
      { krId: "KR-036", krType: "Committed", objectiveId: "O6", objective: "Make the Omni brand synonymous with being world's most advanced wellness club", department: "Marketing", keyResult: "Increase IG followers by 10k per quarter", dataSource: "Marketing dept", baseline: "20500", target: "Baseline + 10k per quarter", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Marketing", reportingTo: "Henry", reviewFrequency: "Monthly", how: "1. Influencer collabs +25% every quarter\n2. High-frequency reels\n3. Transformation content (20/quarter)\n4. Founder thought leadership\n5. Paid growth if quality acceptable", section: "main" },
      { krId: "KR-037", krType: "Committed", objectiveId: "O6", objective: "Make the Omni brand synonymous with being world's most advanced wellness club", department: "Marketing", keyResult: "Track promos and see what works, add ones that work", dataSource: "Marketing dept", baseline: "", target: "Quarterly winning-promo playbook", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Marketing", reportingTo: "Henry", reviewFrequency: "Monthly", how: "1. Create promo tracker by offer, channel, cost, revenue and conversion\n2. Remove weak promos monthly", section: "main" },
      { krId: "KR-038", krType: "Committed", objectiveId: "O7", objective: "Improve operational efficiency and profitability", department: "Operations", keyResult: "Reduce operational cost %", dataSource: "", baseline: "", target: "Set by finance", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "GM / Finance", reportingTo: "GM", reviewFrequency: "Monthly", how: "1. Zero-base top 5 expense lines\n2. Staffing efficiency review\n3. Procurement negotiation\n4. Eliminate low-ROI spend\n5. Monthly variance review by HOD", section: "operational" },
      { krId: "KR-039", krType: "Committed", objectiveId: "O7", objective: "Improve operational efficiency and profitability", department: "Lab", keyResult: "Improve lab efficiency", dataSource: "", baseline: "", target: "Set by Lab", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "WellnessLab / Sadami", reportingTo: "GM", reviewFrequency: "Monthly", how: "1. Batch procurement\n2. Reorder point rules\n3. Standard operating checklist\n4. Reduce repeat/rework\n5. Weekly review of delayed tests", section: "operational" },
      { krId: "KR-040", krType: "Committed", objectiveId: "O7", objective: "Improve operational efficiency and profitability", department: "F&B", keyResult: "Improve F&B margin", dataSource: "", baseline: "", target: "Set by Finance", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "F&B Manager", reportingTo: "GM", reviewFrequency: "Monthly", how: "1. Menu engineering\n2. Remove low-margin SKUs\n3. Increase high-margin attachment\n4. Tighter waste controls\n5. Review contribution margin by SKU monthly", section: "operational" },
      { krId: "KR-041", krType: "Committed", objectiveId: "O8", objective: "Build a high-performing Omni team and culture", department: "People & Culture", keyResult: "Maintain high staff retention rate of over 90%", dataSource: "HR dept", baseline: "", target: "0.9", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "HR", reportingTo: "GM", reviewFrequency: "Quarterly", how: "1. Quarterly check-ins\n2. Manager training\n3. Clear scorecards by role\n4. Onboarding for new hires\n5. Stay interviews for high performers", section: "main" },
      { krId: "KR-042", krType: "Committed", objectiveId: "O8", objective: "Build a high-performing Omni team and culture", department: "People & Culture", keyResult: "Complete quarterly performance reviews", dataSource: "HR dept", baseline: "", target: "1", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "HR", reportingTo: "GM", reviewFrequency: "Quarterly", how: "1. Review calendar locked at start\n2. Simple scorecard template\n3. Deadline reminders\n4. Escalate overdue reviews weekly", section: "main" },
      { krId: "KR-043", krType: "Committed", objectiveId: "O8", objective: "Build a high-performing Omni team and culture", department: "People & Culture", keyResult: "Implement employee feedback loops", dataSource: "HR dept", baseline: "0", target: "1", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "HR", reportingTo: "GM", reviewFrequency: "Monthly", how: "1. Launch pulse survey\n2. Monthly anonymous form\n3. Office-hours with HR/GM\n4. Publish 'you said / we did' updates\n5. Assign owner to each feedback theme", section: "main" },
      { krId: "KR-044", krType: "Committed", objectiveId: "O8", objective: "Build a high-performing Omni team and culture", department: "People & Culture", keyResult: "Reduce time to hire to within 4 weeks", dataSource: "HR dept", baseline: "", target: "4", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "HR", reportingTo: "GM", reviewFrequency: "Monthly", how: "1. Standardize JD templates\n2. Pre-build candidate pipeline\n3. Weekly hiring standup\n4. Interview scorecards\n5. Fast-close process", section: "main" },
      { krId: "KR-045", krType: "Committed", objectiveId: "O8", objective: "Build a high-performing Omni team and culture", department: "People & Culture", keyResult: "Have quarterly meetings with all HODs", dataSource: "HR dept", baseline: "", target: "1", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "GM", reportingTo: "GM", reviewFrequency: "Quarterly", how: "1. Lock quarterly leadership offsite dates\n2. Agenda template\n3. Pre-read scorecards\n4. Action log with owner and due dates", section: "main" },
      { krId: "KR-046", krType: "Committed", objectiveId: "O8", objective: "Build a high-performing Omni team and culture", department: "People & Culture", keyResult: "Have quarterly meetings with individual HODs", dataSource: "HR dept", baseline: "", target: "1", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "GM", reportingTo: "GM", reviewFrequency: "Quarterly", how: "1. Schedule recurring quarterly 1:1s\n2. Use same template\n3. Follow up on action items monthly", section: "main" },
      { krId: "KR-047", krType: "Committed", objectiveId: "O9", objective: "Build a world-class Omni member experience", department: "Operations", keyResult: "Increase member satisfaction", dataSource: "How to track?", baseline: "", target: "Set by Ops", actualCurrent: "2", progressPercent: undefined, status: "Achieved", owner: "GM", reportingTo: "", reviewFrequency: "Weekly", how: "1. Launch always-on pulse survey\n2. Review service failures weekly\n3. Close feedback loop within 48h\n4. Train staff on warm personalized service", notes: "Recommend NPS or 1-10 CSAT", section: "secondary" },
      { krId: "KR-048", krType: "Committed", objectiveId: "O9", objective: "Build a world-class Omni member experience", department: "Operations", keyResult: "Increase onboarding completion rate (Core/All-in)", dataSource: "GymMaster", baseline: "", target: "Set by Ops", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "MEC", reportingTo: "", reviewFrequency: "Weekly", how: "1. Same onboarding actions as O1\n2. Define required steps clearly\n3. Send incomplete list to FOH daily", section: "secondary" },
      { krId: "KR-049", krType: "Committed", objectiveId: "O9", objective: "Build a world-class Omni member experience", department: "Tech & CX", keyResult: "Improve digital onboarding adoption", dataSource: "C&H", baseline: "", target: "Set by Product", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Product", reportingTo: "", reviewFrequency: "Monthly", how: "1. Simplify app first-run flow\n2. QR at reception\n3. Staff-assisted activation\n4. Remove non-essential steps\n5. Completion reminder at 24h and 72h", section: "secondary" },
      { krId: "KR-050", krType: "Committed", objectiveId: "O9", objective: "Build a world-class Omni member experience", department: "Community", keyResult: "Increase number of events & community participation", dataSource: "", baseline: "", target: "Set by Community", actualCurrent: "0.35", progressPercent: undefined, status: "Achieved", owner: "Community Lead", reportingTo: "", reviewFrequency: "Monthly", how: "1. Holiday-based activations\n2. Bring-a-friend events\n3. Free pass days on wellness dates\n4. Partner-hosted talks\n5. Stronger post-event follow-up", section: "secondary" },
      { krId: "KR-051", krType: "Committed", objectiveId: "O9", objective: "Build a world-class Omni member experience", department: "Marketing", keyResult: "Build strategic partnerships", dataSource: "Marketing dept", baseline: "", target: "Set by Marketing", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Marketing", reportingTo: "", reviewFrequency: "Monthly", how: "1. Prioritize hotels, yoga centers, villa groups\n2. Create simple partnership offer\n3. Assign owner and monthly pipeline review", section: "secondary" },
      { krId: "KR-052", krType: "Committed", objectiveId: "O10", objective: "Increase average revenue per member", department: "HWS", keyResult: "Increase HWS bookings +25% per quarter", dataSource: "GymMaster", baseline: "", target: "25% above baseline", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "HWS", reportingTo: "", reviewFrequency: "Monthly", how: "1. Consult pathways by goal\n2. Marketing content on HWS benefits\n3. Monthly workshop with CTA\n4. Trainer referrals\n5. Test recommendation menu\n6. Follow-up booking before member leaves", section: "individual" },
      { krId: "KR-053", krType: "Committed", objectiveId: "O10", objective: "Increase average revenue per member", department: "WellnessLab", keyResult: "Increase supplement sales per WMAM", dataSource: "Finance report", baseline: "", target: "Set by finance", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "WellnessLab", reportingTo: "", reviewFrequency: "Monthly", how: "1. Protocol-linked supplement recommendations\n2. Consult exit recommendations\n3. Display at reception/cafe\n4. Sample packs\n5. Bundles with tests/consults", section: "individual" },
      { krId: "KR-054", krType: "Committed", objectiveId: "O10", objective: "Increase average revenue per member", department: "WellnessLab", keyResult: "Increase IV therapy revenue per WMAM", dataSource: "Finance report", baseline: "", target: "Set by finance", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "WellnessLab", reportingTo: "", reviewFrequency: "Monthly", how: "1. Recovery and travel-targeted IV offers\n2. Attach to HWS consults\n3. Seasonal campaigns\n4. Membership bundle pricing", section: "individual" },
      { krId: "KR-055", krType: "Committed", objectiveId: "O10", objective: "Increase average revenue per member", department: "WellnessLab", keyResult: "Increase massage revenue per WMAM", dataSource: "Finance report", baseline: "", target: "Set by finance", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Marketing / WellnessLab / FOH", reportingTo: "", reviewFrequency: "Monthly", how: "1. Post-class/post-PT recommendations\n2. Recovery bundles\n3. Low-demand slot promotions\n4. Combo offers with sauna/cold/stretch", section: "individual" },
      { krId: "KR-056", krType: "Committed", objectiveId: "O11", objective: "Increase Head of Nutrition activity", department: "Nutrition", keyResult: "Deliver personalized recommendations within 2 days of consult", dataSource: "", baseline: "", target: "2", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Head of Nutrition", reportingTo: "", reviewFrequency: "Weekly", how: "1. Standardized protocol template\n2. AI draft + manual QA\n3. Same-day note completion\n4. Daily queue review\n5. Block admin time after consults", section: "individual" },
      { krId: "KR-057", krType: "Committed", objectiveId: "O11", objective: "Increase Head of Nutrition activity", department: "Nutrition", keyResult: "Deliver 7-day meal plan within 5 business days", dataSource: "", baseline: "", target: "5", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Head of Nutrition", reportingTo: "", reviewFrequency: "Weekly", how: "1. Meal-plan template library\n2. Generator with manual QA\n3. Batch admin windows\n4. Checklist for allergies/preferences/macros", section: "individual" },
      { krId: "KR-058", krType: "Committed", objectiveId: "O11", objective: "Increase Head of Nutrition activity", department: "Nutrition", keyResult: "Increase initial consultations to 5-10/month", dataSource: "", baseline: "", target: "5-10 / month", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Head of Nutrition", reportingTo: "", reviewFrequency: "Monthly", how: "1. New member trigger sequence\n2. Free 15-min wellness audit CTA\n3. Front-desk script\n4. Workshop conversion flow\n5. WA incentives after events", section: "individual" },
      { krId: "KR-059", krType: "Committed", objectiveId: "O11", objective: "Increase Head of Nutrition activity", department: "Nutrition", keyResult: "Achieve >=10% follow-up consultation rate", dataSource: "", baseline: "", target: "0.1", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Head of Nutrition", reportingTo: "", reviewFrequency: "Monthly", how: "1. Sell transformation-support package\n2. Close every consult with next-step booking\n3. Discount 4-follow-up pack\n4. Automate reminders at 2 and 6 weeks", section: "individual" },
      { krId: "KR-060", krType: "Committed", objectiveId: "O11", objective: "Increase Head of Nutrition activity", department: "Nutrition", keyResult: "Achieve >=10% specialty test attach rate", dataSource: "", baseline: "", target: "0.1", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Head of Nutrition", reportingTo: "", reviewFrequency: "Monthly", how: "1. Create test-pathway menu\n2. Symptom-led recommendation logic\n3. Leave-behind explaining test relevance\n4. Follow-up 48h later with booking link", section: "individual" },
      { krId: "KR-061", krType: "Committed", objectiveId: "O11", objective: "Increase Head of Nutrition activity", department: "Nutrition", keyResult: "Increase meal plan conversion rate to >=10% of consults", dataSource: "", baseline: "", target: "0.1", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Head of Nutrition", reportingTo: "", reviewFrequency: "Monthly", how: "1. Goal-based framing\n2. WA follow-up after consult\n3. Discounted first week\n4. Collect blockers when they do not order", section: "individual" },
      { krId: "KR-062", krType: "Committed", objectiveId: "O11", objective: "Increase Head of Nutrition activity", department: "Nutrition", keyResult: "Achieve meal plan satisfaction score >=8.5/10", dataSource: "", baseline: "", target: "8.5", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Head of Nutrition", reportingTo: "", reviewFrequency: "Monthly", how: "1. 7-day feedback form\n2. Fast adjustment option\n3. Taste/variety review\n4. Flag low-scoring menu types monthly", section: "individual" },
      { krId: "KR-072", krType: "Committed", objectiveId: "O1", objective: "Change the lives of 1,000 people by end of 2027", department: "Member Success", keyResult: "Increase average bookings per active member by 10%", dataSource: "GymMaster", baseline: "", target: "10% above baseline", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "MEC", reportingTo: "Connor", reviewFrequency: "Weekly", how: "1. Booking reminders\n2. Class recommendations\n3. Schedule links in MEC messages\n4. 'Book your next session before leaving' script\n5. Waitlist recovery messages", section: "future" },
      { krId: "KR-073", krType: "Committed", objectiveId: "O1", objective: "Change the lives of 1,000 people by end of 2027", department: "Product & Coaching", keyResult: "Increase PWP adherence by 10%", dataSource: "How to track?", baseline: "", target: "10% above baseline", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "HCs", reportingTo: "Connor", reviewFrequency: "Monthly", how: "1. Define adherence score\n2. Weekly check-in form\n3. App reminders\n4. Coach review prompts\n5. Simplify first 2-week protocol\n6. MEC nudges if no follow-up logged", section: "future" },
      { krId: "KR-074", krType: "Committed", objectiveId: "O3", objective: "Build the strongest retention engine in Bali's wellness industry", department: "MEC", keyResult: "Reduce 3 month avg of 4-week member churn by 10%", dataSource: "GymMaster", baseline: "", target: "10% below baseline", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "MEC", reportingTo: "", reviewFrequency: "Monthly", how: "1. Stronger onboarding in first 7 days\n2. Mid-membership engagement messages\n3. Early consult offers\n4. Next step booking before expiry\n5. Capture reason for lapse", section: "future" },
      { krId: "KR-075", krType: "Committed", objectiveId: "O4", objective: "Increase revenue per member", department: "Gym / Trainer / FOH", keyResult: "Increase PT revenue per WMAM", dataSource: "GymMaster", baseline: "", target: "Set by finance", actualCurrent: "", progressPercent: undefined, status: "No data", owner: "Gym / Trainer / FOH", reportingTo: "", reviewFrequency: "Monthly", how: "1. Small group PT / partner PT\n2. Assessment-to-PT handoff\n3. Goal-based PT packages\n4. Progress review every 4 weeks\n5. Trainer scripts for plateauing members", section: "future" },
    ];

    for (const kr of keyResults) {
      await ctx.db.insert("keyResults", kr as any);
    }

    // Seed Update Log
    const updateLogs = [
      { date: "2026-01-31", period: "2026-W01 (Jan | Q1)", krId: "KR-001", actual: 260, notes: "Completed onboardings in January" },
      { date: "2026-01-31", period: "2026-W02 (Jan | Q1)", krId: "KR-002", actual: 182000000, notes: "Clinic revenue IDR" },
      { date: "2026-01-31", period: "2026-W03 (Jan | Q1)", krId: "KR-018", actual: 0.395, notes: "Long-term membership mix" },
      { date: "2026-03-13", period: "2026-W01 (Jan | Q1)", krId: "KR-050", actual: 0.45, notes: "Community event participation" },
      { date: "2026-03-13", period: "2026-W01 (Jan | Q1)", krId: "KR-047", actual: 2, notes: "Member satisfaction score" },
      { date: "2026-03-13", period: "2026-W07 (Feb | Q1)", krId: "KR-050", actual: 0.35, notes: "Community event participation" },
      { date: "2026-03-18", period: "2026-W10 (Mar | Q1)", krId: "KR-025", actual: 0.2, notes: "Long-term membership mix" },
      { date: "2026-03-18", period: "2026-W10 (Mar | Q1)", krId: "KR-031", actual: 23000, notes: "GoJek/Grab daily sales" },
      { date: "2026-03-18", period: "2026-W10 (Mar | Q1)", krId: "KR-003", actual: 4, notes: "Follow-up consultations" },
      { date: "2026-03-18", period: "2026-W10 (Mar | Q1)", krId: "KR-008", actual: 1300, notes: "WMAM count" },
    ];
    for (const log of updateLogs) {
      await ctx.db.insert("updateLog", log);
    }

    // Seed Metric Definitions
    const metrics = [
      { kpi: "WMAM", definition: "Weighted Monthly Active Members from GymMaster membership activity report", sourceSystem: "GymMaster", primaryOwner: "Sales Lead" },
      { kpi: "Tour-to-member conversion", definition: "Members sold from tours / total tours in period", sourceSystem: "FOH / CRM", primaryOwner: "FOH Manager" },
      { kpi: "Long-term membership mix %", definition: "Members on 12-week+ / total active members", sourceSystem: "GymMaster", primaryOwner: "Sales Lead" },
      { kpi: "Revenue per member", definition: "Total revenue in period / WMAM", sourceSystem: "Finance", primaryOwner: "Finance" },
      { kpi: "Onboarding completion %", definition: "Members completing all required onboarding steps / members who started", sourceSystem: "GymMaster / CRM", primaryOwner: "MEC" },
      { kpi: "PWP adherence score", definition: "Members completing >=70% of prescribed actions / members on active PWP", sourceSystem: "App / PWP tracker", primaryOwner: "Product" },
      { kpi: "Renewal conversion rate", definition: "Members who renew / members expiring in period", sourceSystem: "MEC system / GymMaster", primaryOwner: "MEC" },
      { kpi: "Monthly retention rate", definition: "Members still active after period / members active at start adjusted for new joins", sourceSystem: "GymMaster", primaryOwner: "MEC" },
      { kpi: "Win-back rate", definition: "Expired members who reactivate / expired members contacted", sourceSystem: "MEC system", primaryOwner: "MEC" },
      { kpi: "20+ check-in member %", definition: "Members with at least 20 check-ins in month / active members", sourceSystem: "GymMaster", primaryOwner: "MEC" },
      { kpi: "F&B COGS %", definition: "F&B cost of goods sold / F&B revenue", sourceSystem: "Finance", primaryOwner: "F&B Manager" },
      { kpi: "Meal plan conversion rate", definition: "Meal plan orders / nutrition consultations", sourceSystem: "Nutrition tracker", primaryOwner: "Head of Nutrition" },
    ];
    for (const metric of metrics) {
      await ctx.db.insert("metricDefinitions", metric);
    }

    return "Seeded successfully";
  },
});
